name: Run Tests

on:
  push:
    branches: [develop, main, feature/github-actions]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run test suite
        run: wolframscript -file tests/RunAllTests.wl
